name: Tests
on: [push, pull_request]
env:
  CI: true
  RUBY: 2.6.x

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{ env.RUBY }}"

      - name: Disable gem docs
        run: 'echo "gem: --no-document" > ~/.gemrc'

      - name: Set up Ruby cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ env.RUBY }}-${{ hashFiles('Gemfile') }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-${{ env.RUBY }}-${{ hashFiles('Gemfile') }}-${{ hashFiles('Gemfile.lock') }}
            ${{ runner.os }}-gem-${{ env.RUBY }}-

      - name: Set up Bundler
        run: gem install bundler -v "~> 1.17"

      - run: ruby --version
      - run: gem --version
      - run: bundle --version

      - name: Install bundler dependencies
        run: bundle install --deployment --jobs=4 --retry=3 --clean

      - run: bundle exec jekyll build

      - run: bundle exec jekyll doctor

      - name: Run markdownlint
        run: bundle exec mdl --style mdl-style.rb _posts

      - name: Run html-proofer
        run: bundle exec htmlproofer ./_site --allow-hash-href --assume-extension --check-external-hash --check-favicon --check-img-http --check-opengraph --disable-external --empty-alt-ignore --internal-domains "blog.getbootstrap.com"
